"""Added required tables

Revision ID: bfa2d6029d6e
Revises: d7d5b77c66f9
Create Date: 2023-12-23 16:26:20.971101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfa2d6029d6e'
down_revision: Union[str, None] = 'd7d5b77c66f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
